language: C
sudo: enabled
before_script:
 - ./bootstrap
addons:
  apt:
    update: true
    packages:
      - libssl-dev
  homebrew:
    packages:
      - openssl
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libsystemd-dev
      script:
        - ./configure --enable-intf-dummy --enable-intf-dbus
        - make
        - sudo make install
    - os: linux
      dist: trusty
      script:
        - ./configure --enable-intf-dummy
        - make
        - sudo make install
    - os: osx
      osx_image: xcode10.3  
      script:
        - ./configure --enable-intf-dummy
        - make
        - sudo make install
    - os: windows
      before_install:
        - choco uninstall -y mingw
        - choco upgrade --no-progress -y msys2
        - $pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        - $pacman -S --noconfirm autoconf
        - $pacman -S --noconfirm automake
        - $pacman -S --noconfirm autolibtool
        - $pacman -S --noconfirm gcc
        - $pacman -S --noconfirm libreadline-devel
        - $pacman -S --noconfirm openssl-devel
        - taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        - export PATH=/C/tools/msys64/mingw64/bin:$PATH
        - export MAKE=mingw32-make  # so that Autotools can find it
      before_cache:
      - |-
          # https://unix.stackexchange.com/a/137322/107554
          $msys2 pacman --sync --clean --noconfirm

      cache:
          directories:
          - $HOME/AppData/Local/Temp/chocolatey
          - /C/tools/msys64
 
      script:
        - ./configure --enable-intf-lanplus
        - make
      
