language: C
sudo: enabled
before_script:
 - ./bootstrap
addons:
  apt:
    update: true
    packages:
      - libssl-dev
  homebrew:
    packages:
      - openssl
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libsystemd-dev
      script:
        - ./configure --enable-intf-dummy --enable-intf-dbus
        - make
        - sudo make install
    - os: linux
      dist: trusty
      script:
        - ./configure --enable-intf-dummy
        - make
        - sudo make install
    - os: osx
      osx_image: xcode10.3  
      script:
        - ./configure --enable-intf-dummy
        - make
        - sudo make install
    - os: windows
      before_install:
      - choco uninstall -y mingw
      - choco upgrade --no-progress -y cygwin
      - ls -l /c/
      - setup-x86.exe -q -disable-buggy-antivirus --verbose --packages="bash,p7zip,libssl-devel,git,gcc-core,make,diff,autoconf,automake,m4,libtool,libncurses-devel,libreadline-devel"

      script:
        - ./configure --enable-intf-lanplus
        - make
      
