language: C
sudo: enabled
before_script:
  - $shell ./bootstrap

before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco uninstall -y mingw
        choco upgrade --no-progress -y cygwin
        setup-x86.exe -q --upgrade-also --wait --arch="x86_64" --root="c:\tools\cygwin" --packages="wget,bash,p7zip,libssl-devel,git,gcc-core,make,diffutils,autoconf,automake,m4,libtool,libncurses-devel,libreadline-devel" --no-admin
        sleep 300
        export PATH=/usr/local/bin:/usr/bin:$PATH
        export shell="bash.exe " 
        ;;
    esac

addons:
  apt:
    update: true
    packages:
      - libssl-dev
  homebrew:
    packages:
      - openssl
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libsystemd-dev
      script:
        - ./configure --enable-intf-dummy --enable-intf-dbus
        - make
        - sudo make install
    - os: linux
      dist: trusty
      script:
        - ./configure --enable-intf-dummy
        - make
        - sudo make install
    - os: osx
      osx_image: xcode10.3  
      script:
        - ./configure --enable-intf-dummy
        - make
        - sudo make install
    - os: windows
      script:
        - $shell ./configure
        - $shell make
       

