language: C
sudo: enabled
before_script:
  - ./bootstrap

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        $msys2 pacman --sync --clean --noconfirm
        echo --tcp-nodelay >> $APPDATA/.curlrc
        ;;
    esac

before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2 bazel
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export shell="$msys2 -mingw64 -full-path -here -c \$\* --"
        export msys2+=" -msys2 -c \$\* --"
        $msys2 pacman --sync --noconfirm --needed \
                autoconf \
                automake \
                mingw-w64-x86_64-libtool \
                mingw-w64-x86_64-toolchain \
                unzip
        taskkill //IM gpg-agent.exe //F
        export CPPFLAGS=-D__USE_MINGW_ANSI_STDIO=1
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make
        export AR=gcc-ar
        export RANLIB=gcc-ranlib
        for i in {1..1200}
        do
            printf "."; sleep 1;
        done
        echo ""
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

addons:
  apt:
    update: true
    packages:
      - libssl-dev
  homebrew:
    packages:
      - openssl
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libsystemd-dev
      script:
        - ./configure --enable-intf-dummy --enable-intf-dbus
        - make
        - sudo make install
    - os: linux
      dist: trusty
      script:
        - ./configure --enable-intf-dummy
        - make
        - sudo make install
    - os: osx
      osx_image: xcode10.3  
      script:
        - ./configure --enable-intf-dummy
        - make
        - sudo make install
    - os: windows
      script:
        - ./configure
        - make
       

